RauliL/plorth

README.md
docs/index.md
docs/installation.md
docs/language.md
docs/repl.html
mkdocs.yml

Partial documentation is only partial documentation but it's still better than no documentation, so I guess it's time to release some of it.

Add initial WIP documentation

---

include/plorth/context.hpp
include/plorth/runtime.hpp
include/plorth/value-string.hpp
src/context.cpp
src/globals.cpp
src/value-array.cpp
src/value-object.cpp
src/value-quote.cpp
src/value-string.cpp

In #6, I modified the array value class into abstract class so that specialized
implementations of it can be created for different purposes. Now I am about to
do the same for string values for the same purpose, as it in theory can reduce
memory usage and binary size.

Different approach on strings

---

docs/api.md
src/globals.cpp

Improve the grammar.
Fix minor errors.
Clarify minor issues.

Improve API documentation grammar

---

examples/array-reduce.plorth
examples/factorial.plorth
examples/fibonacci.plorth
examples/hello-world.plorth

Use plorth-cli shebang for examples.
Add an example for demonstrating the use of loops.
Add an example demonstrating recursion.

More examples

---

docs/api.md
src/value-object.cpp

Clarify how objects with shared keys are combined.

Improve the grammar of the value object API documentation

---

docs/api.md
src/globals.cpp
tests/test-number.plorth

Add words that correspond to floating point numbers representing infinity and NaN.
refs: https://github.com/RauliL/plorth/issues/34

Implement nan and inf words

---

examples/mandelbrot.plorth

Add an example that demonstrates object prototypes and command line arguments.

Mandelbrot example

---

examples/bottles_of_beer.plorth

Implemenet the song 99 Bottles of Beer in Plorth for submission in:
http://www.99-bottles-of-beer.net/

99 Bottles of Beer example

---

docs/api.md
src/value-boolean.cpp

Introduce new word `?` to `boolean` prototype which can be used as
ternary operator.

Add ternary operator

---

examples/combinators.plorth

Implement the SKI combinator calculus to demonstrate functional features.

Add an example demonstrating currying

---

docs/api.md
src/globals.cpp
src/value-object.cpp
tests/test-globals.plorth

Introduce new global word `instance-of?` into dictionary which can be used to
test whether certain value's prototype chain inherits from an object.

Add instance-of? word to global dictionary

---

docs/api.md
src/globals.cpp
tests/test-globals.plorth

Introduce new words into global dictionary which can be used to construct arrays
from contents of the stack.

Add aray constructor words

---

README.md
docs/index.md

I am going to write more complex IDE based on the current REPL that
works inside browser. Use that as the REPL from now on.

Update REPL location, again

---

docs/language.md

Add a short description for numbers, strings and objects.

Document more value types

---

.editorconfig
editor/plorth.vim

Include Vim syntax highlight definitions of Plorth in the repository.

Add Vim syntax file

---

lib/time/month.plorth
lib/time/weekday.plorth

Populate our runtime library with date related enumeration classes:
month and weekday.

Add date and time related enumerations

---

runtime/collections/set.plorth

Extend our runtime with set implementation, which works as a wrapper for
builtin array type.

Add set implementation

---

libplorth/CMakeLists.txt
libplorth/include/plorth/io-input.hpp
libplorth/include/plorth/io-output.hpp
libplorth/include/plorth/runtime.hpp
libplorth/src/globals.cpp
libplorth/src/io-input.cpp
libplorth/src/io-output.cpp
libplorth/src/runtime.cpp

Move I/O operations into classes which can be overridden.

Allow I/O to be overridden

---

libplorth/src/module.cpp
plorth/src/main.cpp

Add ability to load modules directly from the command line, in the CLI version of Plorth.

Add -r command line flag

---

gui/CMakeLists.txt
gui/include/plorth/gui/dictionary-display.hpp
gui/src/dictionary-display.cpp
gui/src/line-display.cpp
gui/src/line-editor.cpp
gui/src/utils.cpp
gui/src/utils.hpp
gui/src/window.cpp

A feature suggested by @suutari: Live local dictionary display. It displays contents of the local dictionary in a tree view, which is automatically updated as new words are being introduced into it.

Add dictionary display to GUI

---

cli/CMakeLists.txt
cli/src/api.cpp
cli/src/main.cpp
cli/src/repl.cpp
cli/src/utils.cpp
cli/src/utils.hpp
gui/CMakeLists.txt
gui/src/window.cpp
webassembly/CMakeLists.txt
webassembly/src/main.cpp

Instead of just copypasting functions, attempt to reuse them.

Reuse some CLI related code in GUI
