RauliL/plorth

- include/plorth/context.hpp
- include/plorth/runtime.hpp
- include/plorth/value-array.hpp
- src/context.cpp
- src/value-array.cpp
- src/value-object.cpp
- src/value-quote.cpp
- src/value-string.cpp
Instead of always relying on arrays which are only wrappers to std::vector,
introduce abstract array class with multiple different implementations on it.
This in theory could reduce memory usage and binary size, especially with
scripts that combine arrays with each other. Somewhat experimental idea that
could be expanded also to string values.
> Different approach on arrays

- CMakeLists.txt
- include/plorth/config.hpp.in
- include/plorth/context.hpp
- include/plorth/runtime.hpp
- include/plorth/value-number.hpp
- src/context.cpp
- src/globals.cpp
- src/utils.cpp
- src/utils.hpp
- src/value-array.cpp
- src/value-error.cpp
- src/value-number.cpp
- src/value-quote.cpp
- src/value-string.cpp
Supporting only double precision numbers has already caused problems,
especially when comparing numbers against each other. Bring back the
previously removed support for integer numbers, but unlike previously
this time there is only one number class/prototype visible to the
runtime. Details on integer vs. double precision are hidden from the
runtime and visible only to internals of the interpreter, just like in
many JavaScript engines.
> Bring back integer numbers

- include/plorth/context.hpp
- include/plorth/unicode.hpp
- src/compiler.cpp
- src/emscripten.cpp
- src/globals.cpp
- src/main.cpp
- src/module.cpp
- src/unicode.cpp
Instead of having to rely on byte strings that are only assumed to be
UTF-8 encoded, modify the compiler so that it only accepts Unicode
strings. This means that that the decoding must be done by whatever is
calling the compilation, so that the compiler no longer has to worry
about charcter encoding.
This modification is particularily done with WebAssembly target in mind.
Emscripten seems to use UTF-16 as character encoding and is not capable
of handling UTF-8 strings.
> Modify compiler to use Unicode strings

- include/plorth/runtime.hpp
- src/globals.cpp
- src/repl.cpp
- src/runtime.cpp
Instead of always using `std::cout` as the standard output of the
interpreter, add print methods to the `runtime` class, which can be
overridden for obscure platforms such as WebAssembly.
> Add unified print methods to runtime class

- docs/api.md
- src/value-array.cpp
Replace references to copied arrays as self-mutations because the original value cannot be recovered anyway and copying might implicate dup.
> Improve the grammar of the value array API documentation

- include/plorth/context.hpp
- include/plorth/runtime.hpp
- include/plorth/token.hpp
- include/plorth/unicode.hpp
- include/plorth/value-error.hpp
- include/plorth/value.hpp
- src/compiler.cpp
- src/context.cpp
- src/globals.cpp
- src/module.cpp
- src/repl.cpp
- src/runtime.cpp
- src/token.cpp
- src/unicode.cpp
- src/value-array.cpp
- src/value-boolean.cpp
- src/value-error.cpp
- src/value-number.cpp
- src/value-object.cpp
- src/value-quote.cpp
- src/value-string.cpp
- src/value.cpp
C++11 has perfectly usable implementations of characters and strings
that use Unicode code points instead of bytes or "wide characters" that
can be especially painful to use.
Instead of having our own string implementation `unistring` which is
typedef of `std::basic_string<std::uint32_t>`, use the one provided by
standard C++ library. Keep the typedef at least for now for backward
compatibility.
The new `std::u32string` requires some tweaking with stream operators,
but overall it's worth it, especially because we can now use new
`U"..."` string literals.
> Use C++11 Unicode strings instead of own implementation

- src/value-number.cpp
Current division operators perform so called flooring division when both
of the operands are integers, resulting in inconsistensies like
10 3 /      #=> 1
10 3.0 /    #=> 3.33333
10 3 %      #=> 0
10 3.0 %    #=> 1
Solution is to ditch the flooring division and always use real division
instead, just like JavaScript and Python 3 does.
> Use real division operators instead of flooring ones

- .editorconfig
Editor config is currently missing maximum line length setting, which should be 79. Fixes #20.
> Add maximum line length to .editorconfig

- src/utils.cpp
- src/value-number.cpp
- tests/test-number.plorth
Make sure that numbers in exponential notation are recognized and parsed correctly.
Remove checks for floating point underflow and overflow. Those are known as 0 and inf respectively.
> Add support for exponential notation

- src/value-array.cpp
- src/value-string.cpp
- tests/test-array.plorth
- tests/test-string.plorth
Due to the weird way array and string indices are tested in Plorth, it's
possible to segfault the interpreter by retrieving item 0 (or any other
index actually) from empty array or string. These modifications prevent
that and add the problematic operations into test cases.
> Fix indexing problem with zero sized containers

- docs/api.md
- src/value-array.cpp
- tests/test-array.plorth
Introduce two new words, `push` and `pop` into array prototype which
allows use of arrays as they were additional data stacks.
> Add push and pop words to array prototype

- docs/api.md
- src/value-quote.cpp
- tests/test-quote.plorth
Introduce two words into quote prototype inspired by the Factor programming
language: dip and 2dip. These words can be used to call quotes with "hidden"
values that will be placed back onto the stack once the quote execution has been
completed.
> Add dip and 2dip words to quote prototype

- src/runtime.cpp
Not every builtin prototype should inherit directly from `object`
prototype, even though even that doesn't work properly as name of the
property of parent prototype should be `__proto__` instead of `prototype`.
Prototype of prototypes should however be `object`, which is currently
isn't. Fix that as well.
> Fix prototype inheritance for builtin prototypes

- src/globals.cpp
Constants are currently broken. If you place quote into local dictionary
as constant, the quote will be called instead of placed onto the stack
when you access it.
> Fix constants

- src/main.cpp
When you write `plorth-cli --version` it currently prints out some kind of
pointer instead of the version string, because it isn't UTF-8 encoded.
> Fix --version command line switch

- include/plorth/context.hpp
- include/plorth/runtime.hpp
- src/globals.cpp
- src/module.cpp
- src/runtime.cpp
- src/value-symbol.cpp
Modify local and global dictionaries so that they only allow quotes to be placed on them. Also fixes three possible null pointer errors.
> Allow only quotes in dictionaries

- include/plorth/context.hpp
- scripts/run-tests.sh
- src/main.cpp
- src/module.cpp
- src/utils.cpp
- src/utils.hpp
Relative imports always use CWD of the interpreter process as starting
point from where to look for the module. This is incorrect, as it should
be always from directory of the script file which is currently being
executed. Refactor module search routine so that it supports this.
Fixes: #64
> Fix relative imports

- CMakeLists.txt
- examples/array-reduce.plorth
- examples/bottles-of-beer.plorth
- examples/combinators.plorth
- examples/factorial.plorth
- examples/fibonacci.plorth
- examples/hello-world.plorth
- examples/mandelbrot.plorth
- examples/object-immutability.plorth
- scripts/run-tests.sh
The real reason why name of Plorth interpreter is currently `plorth-cli`
is because I want to separate the interpreter library and executable.
CMake cannot handle targets with the same name, so I cannot have both
library and executable called `plorth`. However, you can override the
executable name with this simple trick which gives us both library and
executable with the same name.
> Rename plorth-cli executable to just plorth

- lib/ansi-terminal.plorth
Add new runtime module called `ansi-terminal` which contains various
ANSI terminal escape sequences as constants and words for constructing
them.
> Add ANSI terminal escape sequences as module

- CMakeLists.txt
- include/plorth/config.hpp.in
- include/plorth/context.hpp
- include/plorth/runtime.hpp
- include/plorth/value-number.hpp
- src/context.cpp
- src/globals.cpp
- src/repl.cpp
- src/utils.cpp
- src/utils.hpp
- src/value-array.cpp
- src/value-number.cpp
- src/value-string.cpp
64-bit integers in WebAssembly result in poor performance as they have
to be emulated as the platform doesn't directly support them. For this
reason, I added an option to choose between 64-bit and 32-bit integer
types, which by default uses 64-bit integers.
> Add option to use 32-bit integers

- src/value-array.cpp
- src/value-string.cpp
Add implementations of reversed arrays and strings that can be used when
word `reverse` is applied to array or string, which hopefully reduces
memory usage especially when the containers are large.
> Optimize reversed containers

- include/plorth/context.hpp
- include/plorth/memory.hpp
- include/plorth/plorth.hpp
- include/plorth/ref.hpp
- include/plorth/unicode.hpp
- include/plorth/value.hpp
- src/main.cpp
Include required predeclarations and includes into header files so that
they can be either included individually as is done now, or so that the
`plorth/plorth.hpp` header can be the only header needed to include to
embed the interpreter into C++ application.
> Reorganize header files

- src/globals.cpp
While `std::time()` function usually returns number of seconds since the
epoch, the specification says that whatever this function returns is
actually implementation specific, thus it's not very portable function
to use for such purpose.
Luckily C++11 chrono API provides us function which should return number
of seconds since epoch for every platform.
> Use C++11 API for epoch retrieval

- CMakeLists.txt
- include/plorth/context.hpp
- include/plorth/position.hpp
- include/plorth/value-error.hpp
- src/compiler.cpp
- src/context.cpp
- src/main.cpp
- src/module.cpp
- src/position.cpp
- src/value-error.cpp
Include optional source code position in errors, so that position where the error has occurred can be displayed. Currently it contains filename as well as line and column numbers.
Unfortunately this can currently be implemented only with syntax errors. Proper way to do this would be storing source code position into each symbol, which would then be transferred to interpreter when the symbol is being executed. This is not possible currently because we cache symbols to reduce resource usage.
Fixes #65
> Source code location

- docs/api.md
- include/plorth/context.hpp
- include/plorth/runtime.hpp
- include/plorth/value-symbol.hpp
- src/compiler.cpp
- src/context.cpp
- src/main.cpp
- src/value-symbol.cpp
Improve error reporting and source code position tracking even more by adding source code positions into symbols and execution contexts. Every time symbol is executed, source code position of the execution context is updated with the symbol's source code position, which is used as default source code position when new exceptions are being constructed. Unfortunately, this feature remains disabled if you have symbol caching enabled.
Fixes #65
> Even more improved error reporting

- src/compiler.cpp
If line comment does not end with line terminator, parsing such comment
will currently result in infinite loops. I really need to write parser
tests soon.
> Fix infinite loop in comment parsing

- include/plorth/value-array.hpp
- include/plorth/value-string.hpp
- src/value-array.cpp
- src/value-string.cpp
Make the C++ API more C++ by implementing very simple iterator classes
for both `array` and `string`, so that they can be used in range based
`for` loop.
> Add iterators to string and array

- src/value-array.cpp
- src/value-string.cpp
1. Reduce memory usage on array and string repetitions by reusing the existing array and string instances.
2. Optimize array and string concatenations by caching size of the concatenated array (or string) and making the size retrieval methods inline.
> String and array optimizations

- docs/api.md
- src/value-array.cpp
- tests/test-array.plorth
Introduce word `>quote` to array prototype which converts array into
quote. This opens new wacky possibilities such as lazy evaluation and
emulation of variables.
> Add ability to convert arrays into quotes

- src/value-array.cpp
- src/value-string.cpp
Index checking for strings and arrays is currently flawed, as it allows
length plus one access.
> Fix string and array index checking

- libplorth/include/plorth/value.hpp
- libplorth/src/value.cpp
Printing plorth values into C++ streams is currently broken because of
the switch to smart pointers. Providing `<<` operator that works
directly on pointers fixes the issue.
> Fix print operator with smart pointers

- Doxyfile
Paths in `Doxyfile` still point to old locations, which have been since
changed. Update `Doxyfile` to fix this.
> Fix paths in Doxyfile

- README.md
- docs/CNAME
- docs/installation.md
Update CLI interpreter binary name and move `CNAME` file from `gh-pages` branch into `docs` directory.
> Documentation fixes

- docs/api.md
- libplorth/include/plorth/runtime.hpp
- libplorth/include/plorth/unicode.hpp
- libplorth/include/plorth/value-error.hpp
- libplorth/src/globals.cpp
- libplorth/src/runtime.cpp
- libplorth/src/unicode.cpp
- libplorth/src/value-error.cpp
- scripts/generator-apidoc.pl
Introduce two new words; `read` and `nread` which can be used to read text encoded in UTF-8 from standard input.
> Add words for reading from standard input

- libplorth/CMakeLists.txt
- libplorth/include/plorth/context.hpp
- libplorth/include/plorth/dictionary.hpp
- libplorth/include/plorth/runtime.hpp
- libplorth/src/compiler.cpp
- libplorth/src/context.cpp
- libplorth/src/dictionary.cpp
- libplorth/src/exec.cpp
- libplorth/src/globals.cpp
- libplorth/src/module.cpp
- libplorth/src/runtime.cpp
- libplorth/src/value-word.cpp
- plorth/src/repl.cpp
Unify dictionaries between execution contexes and runtime by introducing
dictionary container class which can be used to store words.
> Add dictionary container class

- libplorth/include/plorth/context.hpp
- libplorth/include/plorth/memory.hpp
- libplorth/include/plorth/runtime.hpp
- libplorth/src/context.cpp
- libplorth/src/memory.cpp
- libplorth/src/module.cpp
- libplorth/src/runtime.cpp
- plorth-webassembly/src/main.cpp
- plorth/src/main.cpp
Do not expose the constructors of `runtime` and `context` classes, but
instead introduce factory methods for constructing them. For shit and
giggles mostly, I just think that this API is more neater as you don't
have to directly deal with pointers to the memory manager or anything.
> Use factory methods instead of constructors

- libplorth/include/plorth/value-array.hpp
- libplorth/include/plorth/value-string.hpp
- libplorth/src/value-array.cpp
- libplorth/src/value-string.cpp
I see no point keeping classes such as `array_iterator` and
`string_iterator` inside `plorth` namespace, when they should be
declared inside `array` and `string` classes instead.
> Move iterator classes inside the container classes

- docs/api.md
- libplorth/src/value-array.cpp
- libplorth/src/value-string.cpp
Introcuce `flatten` and `nflatten` methods into array prototype which can be used to flatten recursive arrays.
> Array flattening methods

- gui/include/plorth/gui/dictionary-display.hpp
- gui/include/plorth/gui/line-editor.hpp
- gui/include/plorth/gui/window.hpp
- gui/src/dictionary-display.cpp
- gui/src/line-editor.cpp
- gui/src/window.cpp
Modify the dictionary display component so that it signals when an entry
has been double clicked by the user. Then attach to this signal in the
main window, so that source code of the selected word will be placed
into the line editor, thus making the dictionary entries kinda editable.
> Make dictionary entries "editable" in GUI

- gui/CMakeLists.txt
- gui/include/plorth/gui/context.hpp
- gui/include/plorth/gui/window.hpp
- gui/src/context.cpp
- gui/src/main.cpp
- gui/src/utils.hpp
- gui/src/window.cpp
Moving the runtime and execution context into separate class away from
the main window in the GUI makes the code more cleaner, and hopefully
even reusable.
> Move context away from the main window in GUI

- .gitmodules
- README.md
- docs/installation.md
- plorth/CMakeLists.txt
- plorth/src/main.cpp
Plorth doesn't have proper CLI right now, instead it reads user input with `std::getline` function, which doesn't provide things you would except from a modern command line application, such as proper keybindings and history. For a while, I thought about implementing such functionality with GNU readline library, but instead I chose linenoise instead, which is minimal embeddable readline replacement that provides all the functionality I need without any unnecessary bloat.
> Use linenoise library for improved CLI UX

- libplorth/include/plorth/context.hpp
- libplorth/include/plorth/dictionary.hpp
- libplorth/include/plorth/runtime.hpp
- libplorth/include/plorth/value-object.hpp
- libplorth/src/compiler.cpp
- libplorth/src/context.cpp
- libplorth/src/eval.cpp
- libplorth/src/globals.cpp
- libplorth/src/module.cpp
- libplorth/src/runtime.cpp
- libplorth/src/value-object.cpp
- libplorth/src/value.cpp
- tests/test-object.plorth
Hide implementation details on class `object`, just like have been previously done to `array` and `string` classes. They do not need to be part of the public API and allows us to do various optimizations.
> Redesign object class
